# Caso de Negocio: Clasificación de Clientes

## Modelo RFM - Modelo K-Means

In [ ]:
# Fase Importación de Datos
## Importar Librerías
import pandas as pd
import numpy as np

#Importar Base de datos de Parques
df_parques = pd.read_csv('usos_parques_2024_2025.csv')
df_parques.head()

,code_anon,genero,fechanacimiento,fecha,hora,codsede,codproducto,valor_neto,valor_descuento,tarifa,grupo,tipo_venta
0,ID_d91be8edb096,Femenino,1977-01-09,2025-05-25,11.0,721.0,24.0,0.0,4700,TA,Cortesias web 2-Apl,Individual
1,ID_6d1b7b46e8f8,Masculino,1971-12-20,2025-05-25,11.0,722.0,24.0,4800.0,0,TB,NaN,Individual
2,ID_565bd74de162,Masculino,1963-10-28,2025-05-25,8.0,721.0,24.0,21400.0,0,TC,Adulto mayor no afi. parques,Individual
3,ID_ca7d0706f01b,Femenino,2006-03-16,2025-05-25,10.0,723.0,504.0,3100.0,0,TB,NaN,Individual
4,ID_b7edbab69874,Femenino,1988-02-07,2025-05-25,16.0,723.0,504.0,4300.0,0,TC,NaN,Individual

In [3]:
df_parques2 = pd.read_csv('usos_parques_2024_2025.2.csv')
df_parques2.head()

,code_anon,genero,fechanacimiento,fecha,hora,codsede,codproducto,valor_neto,valor_descuento,tarifa,grupo,tipo_venta
0,ID_9301202a1548,Masculino,2014-04-28,2024-01-02,9.0,721.0,24.0,4500.0,0,TA,NaN,Individual
1,ID_7f5174f88b44,Femenino,1985-11-29,2024-01-02,9.0,721.0,24.0,4500.0,0,TA,NaN,Individual
2,ID_06a5d7f57dc2,Masculino,2012-07-21,2024-01-02,13.0,723.0,24.0,4500.0,0,TA,NaN,Individual
3,ID_d7a80202670e,Masculino,1975-07-17,2024-01-02,9.0,721.0,24.0,4500.0,0,TA,NaN,Individual
4,ID_bcf0ee23d281,Masculino,1997-12-23,20240102,11.0,779.0,24.0,6500.0,0,TB,NaN,Individual